# Generated by Django 3.2 on 2023-10-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(db_index=True, upload_to='api/media', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='processed',
            field=models.BooleanField(default='False', verbose_name='Обработан'),
        ),
    ]
