version: '3'

volumes:
  pg_data:
  static:
  media:
  celery:
  redis:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: julianastr/uploading_and_processing_files_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
      - redis

  nginx:
    image: julianastr/uploading_and_processing_files_nginx
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/app/media
    ports:
      - 9000:80

  celery:
    image: julianastr/uploading_and_processing_files_backend
    command: celery worker --app=Uploading_and_processing_files --loglevel=info
    volumes:
      - ./Uploading_and_processing_files:/usr/src/app
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:5-alpine
