version: '3'

volumes:
  pg_data:
  static:
  media:
  web:
  celery:
  redis:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
      - redis

  nginx:
    build: ./nginx/
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/app/media
    ports:
      - 9000:80

  web:
    build: ./backend/
    env_file: .env
    volumes:
      - ./backend/Uploading_and_processing_files:/usr/src/app
    depends_on:
      - redis

  celery:
    build: ./backend/
    command: celery worker --app=Uploading_and_processing_files --loglevel=info
    volumes:
      - ./backend/Uploading_and_processing_files:/usr/src/app
    env_file: .env
    depends_on:
      - web
      - redis

  redis:
    image:
      redis:5-alpine